package com.mcp.service;

import com.mcp.config.JiraApiConfiguration;
import com.mcp.dto.IssueManagementDTO;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.ai.tool.annotation.Tool;
import org.springframework.http.*;
import org.springframework.stereotype.Service;
import org.springframework.web.util.UriComponentsBuilder;

import java.net.URI;
import java.util.HashMap;
import java.util.Map;

@Service
public class IssueManagementService extends BaseJiraService{

    private static final Logger logger = LoggerFactory.getLogger(IssueManagementService.class);

    public IssueManagementService(JiraApiConfiguration jiraApiConfiguration) {
        super(jiraApiConfiguration);
    }

    @Tool(name = "create_issues",description = "Create a new Jira issue" +
            "@param issueData An instance of {@link IssueManagementDTO.CreateIssueRequest} containing the details of the issue to be created"+
            "@return An instance of {@link IssueManagementDTO.CreateIssueResponse} containing the details of the created issue."+
            "If the issue creation fails, an empty {@link IssueManagementDTO.CreateIssueResponse} is returned." +
            "Example json sent: {\n" +
            "  \"fields\": {\n" +
            "    \"project\": {\n" +
            "      \"key\": \"DEMO\"\n" +
            "    },\n" +
            "    \"summary\": \"Creating From Collection\",\n" +
            "    \"description\": {\n" +
            "      \"type\": \"doc\",\n" +
            "      \"version\": 1,\n" +
            "      \"content\": [\n" +
            "        {\n" +
            "          \"type\": \"paragraph\",\n" +
            "          \"content\": [\n" +
            "            {\n" +
            "              \"type\": \"text\",\n" +
            "              \"text\": \"This is an autogenerated issue from a demo.\"\n" +
            "            }\n" +
            "          ]\n" +
            "        }\n" +
            "      ]\n" +
            "    },\n" +
            "    \"issuetype\": {\n" +
            "      \"name\": \"Task\"\n" +
            "    }\n" +
            "  }\n" +
            "}")
    public String createIssue(IssueManagementDTO.CreateIssueRequest issueData) {
        String endpoint = "/issue";
        System.out.println("Issue data received : " + issueData);
        URI uri = UriComponentsBuilder.fromUriString(this.jiraApiConfiguration.apiUrl() + endpoint)
                .build()
                .encode()
                .toUri();

        try {
            // Send POST request
            ResponseEntity<IssueManagementDTO.CreateIssueResponse> response = restClient.post()
                    .uri(uri)
                    .headers(httpHeaders -> httpHeaders.addAll(headers))
                    .body(issueData)
                    .retrieve()
                    .toEntity(IssueManagementDTO.CreateIssueResponse.class);
            logger.info("Response received: {}", response);
            logger.info("response.getBody(): {}", response.getBody());
            // Return created issue data
            return "Issue created with key: "+response.getBody();
        } catch (Exception e) {
            logger.error("Error creating JIRA issue: {}", e.getMessage());
            return "It failed to create issue";
        }
    }

    @Tool(name = "update_issue",description = "Update an existing Jira issue")
    public ResponseEntity<Void> updateIssue(String issueKey, IssueManagementDTO.CreateIssueRequest issueData) {
        String endpoint = "/issue/" + issueKey;

        URI uri = UriComponentsBuilder.fromUriString(this.jiraApiConfiguration.apiUrl() + endpoint)
                .build()
                .encode()
                .toUri();

        try {
            // Send PUT request
            ResponseEntity<Void> response = restClient.put()
                    .uri(uri)
                    .headers(httpHeaders -> httpHeaders.addAll(headers))
                    .body(issueData)
                    .retrieve()
                    .toEntity(Void.class);

            // Return updated issue data
            return response.getStatusCode() == HttpStatus.NO_CONTENT ? ResponseEntity.noContent().build() : ResponseEntity.status(HttpStatus.BAD_REQUEST).build();
        } catch (Exception e) {
            logger.error("Error updating JIRA issue: {}", e.getMessage());
            return ResponseEntity.status(HttpStatus.BAD_REQUEST).build();
        }
    }

    @Tool(name = "comment_issue",description = "Add a comment to an existing Jira issue")
    public IssueManagementDTO.AddCommentResponse addComment(String issueKey, String comment) {
        String endpoint = "/issue/" + issueKey + "/comment";
        Map<String, Object> data = new HashMap<>();
        data.put("body", comment);

        URI uri = UriComponentsBuilder.fromUriString(this.jiraApiConfiguration.apiUrl() + endpoint)
                .build()
                .encode()
                .toUri();

        try {
            // Send POST request
            ResponseEntity<IssueManagementDTO.AddCommentResponse> response = restClient.post()
                    .uri(uri)
                    .headers(httpHeaders -> httpHeaders.addAll(headers))
                    .body(data)
                    .retrieve()
                    .toEntity(IssueManagementDTO.AddCommentResponse.class);

            // Return added comment data
            return response.getBody() != null ? response.getBody() : new IssueManagementDTO.AddCommentResponse("", "");
        } catch (Exception e) {
            logger.error("Error adding comment to JIRA issue: {}", e.getMessage());
            return new IssueManagementDTO.AddCommentResponse("", "");
        }
    }

}
